# http://www.appveyor.com/docs/appveyor-yml

# version format
version: 1.1.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Build worker image (VM template)
image: Visual Studio 2015

# Assembly Info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#Build Relase instead of Debug
configuration: Release

artifacts:
  - path: Tulpep.NotificationWindow\bin\Release\Tulpep.NotificationWindow.dll
    name: Tulpep.NotificationWindow.dll
  - path: '**\Tulpep.NotificationWindow*.nupkg'
    name: Tulpep.NotificationWindow.nupkg

after_test:
  - ps: .\Nuget\build.ps1

#Publish NuGet
deploy:
  provider: NuGet
  api_key:
    secure: nGvHoLNrH4j9xxQF0wMmlLRlVkflplJhlPqn9VMcv1llIQi+PQYVKhpuOcMJqHnh
  artifact: /.*\.nupkg/
  on:
    branch: master
